# -*- coding: utf-8 -*-
"""API Directory.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hYGJp5c_5rahECL2PV4PjVKKVaCdr5oB
"""

from bs4 import BeautifulSoup as bs
from google.colab import files
import requests
import pandas as pd

url = "https://www.programmableweb.com/apis/directory?page="

Directory = []

for page in range(0,853):
    response = requests.get(url+str(page))
    soup = bs(response.text,"html.parser")
    API_directories = soup.find_all('tr',class_= {'odd','even'})
    
    for API_directory in API_directories:
        Temp_Directory = {}
        Cells = API_directory.find_all("td")
        Temp_Directory['API_names'] = Cells[0].get_text()
        Temp_Directory['Descriptions'] = Cells[1].get_text()
        Temp_Directory['Categories'] = Cells[2].get_text()
        Temp_Directory['Followers'] = Cells[3].get_text()
        Directory.append(Temp_Directory)

df = pd.DataFrame(Directory)

df

df.to_csv('API_directory.csv', index=False)

files.download('API_directory.csv')